# Server config
server.port=8080

# OAuth config
google.client-id=925344537056-9jm6vkq3tnnshde8hclgvt1f45o199an.apps.googleusercontent.com
google.client-secret=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
google.redirect-uri=http://localhost:8080/callback

# Database config (H2 in-memory for prototype)
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:cs30db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
