server.port=8443

app.timezone=America/Los_Angeles

server.ssl.enabled=true
server.ssl.certificate=/etc/ssl/cs30/fullchain.pem
server.ssl.certificate-private-key=/etc/ssl/cs30/privkey.pem

server.compression.enabled=true
server.compression.mime-types=text/html,text/css,text/plain,application/javascript,text/javascript,application/json,application/wasm,image/svg+xml
server.compression.min-response-size=1024

spring.datasource.url=jdbc:postgresql://localhost:5432/cs30db
spring.datasource.username=cs30
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

google.client-id=160623963910-reen5hga1n171tjoc224snv4ktiv9i8m.apps.googleusercontent.com
google.client-secret=${GOOGLE_CLIENT_SECRET}
google.redirect-uri=https://sjsu.cs30.app:8443/callback

git.server.ssh-host=localhost
git.server.ssh-user=divyam

judge.url=http://localhost:8000

server.servlet.session.timeout=1h

cs30.backend.url=https://sjsu.cs30.app:8443

cs30.allowed-ips=

docker.path=/usr/bin/docker

editor.max-custom-test-cases=1
