server.port=443

app.timezone=America/Los_Angeles
#SSL
server.ssl.enabled=true
server.ssl.certificate=/etc/ssl/cs30/fullchain.pem
server.ssl.certificate-private-key=/etc/ssl/cs30/privkey.pem

server.compression.enabled=true
server.compression.mime-types=text/html,text/css,text/plain,application/javascript,text/javascript,application/json,application/wasm,image/svg+xml
server.compression.min-response-size=1024
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cs30db
spring.datasource.username=cs30
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

google.client-id=160623963910-reen5hga1n171tjoc224snv4ktiv9i8m.apps.googleusercontent.com
google.client-secret=${GOOGLE_CLIENT_SECRET}
google.redirect-uri=https://sjsu.cs30.app/callback

git.server.ssh-host=localhost
git.server.ssh-user=divyam
logging.level.com.cs30.server.service.GitService=DEBUG

# Judge properties
judge.url=http://localhost:8000
judge.image=ghcr.io/sjsu-cs-systems-group/judge-sandbox:latest
judge.sandbox.memory-mb=2560
judge.limits.max-custom-cases=3
docker.path=/usr/bin/docker

server.servlet.session.timeout=1h
# IP whitelist
cs30.allowed-ips=

# Frontend properties
cs30.backend.url=https://sjsu.cs30.app
editor.max-custom-test-cases=3
