#!/usr/bin/env python3
"""One source of truth for Phase 1 load-test fixtures: the course roster, the seeded
login_sessions rows, and k6's --local-ips list all come from here, so they can't drift
out of sync with each other.

The course's lab active window is always [now, now + 1 month) — deliberately decoupled from
however long any given k6 invocation's simulated session is (that's k6's own LAB_MINUTES env
var). The lab just needs to stay open across however many quick/full test runs happen over the
testing period; it's not meant to model a real 75-minute class period itself.

Usage:
    python3 gen-fixtures.py --count 100 --ip-base 127.0.0 --ip-start 2 \
        --repo-base /home/joshini/loadtest --out-dir .

Produces, in --out-dir:
    students.json          # [{email, ip, token}, ...] — read by the k6 script
    loadtest-course.yaml     # full course YAML, ready for `addcourse --course-file`
    seed-sessions.sql       # INSERT statements for login_sessions in the throwaway DB
    local-ips.txt           # comma-joined IP list, for `k6 run --local-ips=$(cat local-ips.txt)`
"""
import argparse
import json
import os
import uuid
from datetime import datetime, timedelta

LAB_WINDOW_DAYS = 30
LANGUAGE = "python"
PROBLEM_NAME = "sum-two-numbers"
SESSION_PLATFORM = "web"


def build_students(count, ip_base, ip_start):
    return [
        {
            "email": f"loadtest-student-{i:04d}@example.test",
            "ip": f"{ip_base}.{ip_start + i - 1}",
            "token": str(uuid.uuid4()),
        }
        for i in range(1, count + 1)
    ]


def write_students_json(students, out_dir):
    with open(f"{out_dir}/students.json", "w") as f:
        json.dump(students, f, indent=2)


def write_course_yaml(students, lab_start, repo_base, course_id, out_dir):
    lab_end = lab_start + timedelta(days=LAB_WINDOW_DAYS)
    fmt = "%Y-%m-%dT%H:%M:%S"
    student_lines = "\n".join(f"      - {s['email']}" for s in students)
    student_git_repo = f"{repo_base}/students"
    problem_git_repo = f"{repo_base}/problems"
    yaml_text = f"""code: "{course_id}"
year: {lab_start.year}
semester: "Loadtest"
startDate: "{lab_start.date().isoformat()}"
endDate: "{lab_end.date().isoformat()}"
studentGitRepo: {student_git_repo}
problemGitRepo: {problem_git_repo}
language: {LANGUAGE}
sections:
  - number: 1
    ta: null
    labs:
      - number: 1
        startDateTime: "{lab_start.strftime(fmt)}"
        endDateTime: "{lab_end.strftime(fmt)}"
        problems:
          - name: "{PROBLEM_NAME}"
            language: {LANGUAGE}
    students:
{student_lines}
"""
    with open(f"{out_dir}/loadtest-course.yaml", "w") as f:
        f.write(yaml_text)


def write_seed_sql(students, out_dir):
    lines = [
        "-- Generated by gen-fixtures.py — run against the throwaway cs30_loadtest DB only.",
        "-- logged_in_at is supplied explicitly: Kotlin-side LocalDateTime.now() defaults don't",
        "-- become DB column defaults, so a raw INSERT must set it.",
    ]
    for s in students:
        lines.append(
            "INSERT INTO login_sessions "
            "(token, student_email, ip_address, platform, logged_in_at, last_heartbeat_at, logged_out_at) "
            f"VALUES ('{s['token']}', '{s['email']}', '{s['ip']}', '{SESSION_PLATFORM}', now(), now(), NULL);"
        )
    with open(f"{out_dir}/seed-sessions.sql", "w") as f:
        f.write("\n".join(lines) + "\n")


def write_local_ips(students, out_dir):
    with open(f"{out_dir}/local-ips.txt", "w") as f:
        f.write(",".join(s["ip"] for s in students))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=100)
    parser.add_argument("--ip-base", default="127.0.0", help="first three octets; last octet increments per student")
    parser.add_argument("--ip-start", type=int, default=2, help="last octet for student 1 (127.0.0.1 is the default loopback)")
    parser.add_argument("--repo-base", default="/home/joshini/loadtest", help="parent dir for the disposable students/problems git repos on the server")
    parser.add_argument("--course-id", default="CS30-LOADTEST", help="use a distinct id (e.g. CS30-LOADTEST-QUICK) for a quick pass vs. the full run, so re-running addcourse doesn't collide with an already-seeded course of the same code")
    parser.add_argument("--out-dir", default=".")
    args = parser.parse_args()

    lab_start = datetime.now()

    os.makedirs(args.out_dir, exist_ok=True)
    students = build_students(args.count, args.ip_base, args.ip_start)
    write_students_json(students, args.out_dir)
    write_course_yaml(students, lab_start, args.repo_base, args.course_id, args.out_dir)
    write_seed_sql(students, args.out_dir)
    write_local_ips(students, args.out_dir)

    print(f"Generated {len(students)} students in {args.out_dir}/:")
    print("  students.json, loadtest-course.yaml, seed-sessions.sql, local-ips.txt")
    print(f"Course: {args.course_id}")
    print(f"Lab window (course active period, independent of k6's LAB_MINUTES): "
          f"{lab_start.isoformat()} -> {(lab_start + timedelta(days=LAB_WINDOW_DAYS)).isoformat()}")
    print(f"Repos: {args.repo_base}/students, {args.repo_base}/problems")


if __name__ == "__main__":
    main()
